### ISSUE TITLE
Error occur in run.py line21:call("clear")

### ISSUE THREAD

**Issue by linrio** [SullyChen/Autopilot-TensorFlow#17]
I follow  **Use python `run.py `to run the model on a live webcam feed** . 
platform: Win10.
python version:3.5
tesorflow version:1.0 
Then it occured the error:
```
Traceback (most recent call last):
  File "G:/codes/tensorflow2/Autopilot-TensorFlow/run.py", line 21, in <module>
    call("clear")
  File "D:\Program Files (x86)\Miniconda3\lib\subprocess.py", line 557, in call
    with Popen(*popenargs, **kwargs) as p:
  File "D:\Program Files (x86)\Miniconda3\lib\subprocess.py", line 947, in __init__
    restore_signals, start_new_session)
  File "D:\Program Files (x86)\Miniconda3\lib\subprocess.py", line 1224, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] The system cannot find the file specified
```
What happen?

**Comment by numpad0** [comment]
I had that too. That line is safe to remove so that's the easiest fix. This is happening because Windows Command Prompt uses "cls" rather than "clear", but that line is just cosmetic anyway.

**Comment by linrio** [comment]
@numpad0 Ok, I have noted line `call("clear")`, now the errror disappears.
