### ISSUE TITLE
tensorflow error...

### ISSUE THREAD

**Issue by yghcats** [SullyChen/Autopilot-TensorFlow#21]
Hi, which version of tensorflow do you use?

My tensorflow is version 0.8

Error occurred：
Traceback (most recent call last):
  File "train.py", line 5, in <module>
    import model
  File "/home/gtx-140601/Autopilot-TensorFlow-master/model.py", line 88, in <module>
    y = tf.mul(tf.atan(tf.matmul(h_fc4_drop, W_fc5) + b_fc5), 2) #scale the atan output
AttributeError: 'module' object has no attribute 'atan'

**Comment by 15751064254** [comment]
tf.mul, tf.sub and tf.neg are deprecated in favor of tf.multiply, tf.subtract and tf.negative.
