### ISSUE TITLE
I am getting error while running "python run.py"

### ISSUE THREAD

**Issue by ramanagak** [SullyChen/Autopilot-TensorFlow#24]
2017-07-07 19:03:25.099477: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.1 instructions, but these are available on your machine and could speed up CPU computations.
Traceback (most recent call last):
  File "run.py", line 19, in <module>
    image = scipy.misc.imresize(frame, [66, 200]) / 255.0
  File "/usr/local/lib/python2.7/dist-packages/scipy/misc/pilutil.py", line 480, in imresize
    im = toimage(arr, mode=mode)
  File "/usr/local/lib/python2.7/dist-packages/scipy/misc/pilutil.py", line 289, in toimage
    raise ValueError("'arr' does not have a suitable array shape for "
ValueError: 'arr' does not have a suitable array shape for any mode.

**Comment by Parasgr7** [comment]
I also faced this error because i didn't plug in any usb camera.
Once i plugged camera in, this command worked great.
