### ISSUE TITLE
TypeError: Variables to save should be passed in a dict or a list: ./logs

### ISSUE THREAD

**Issue by anianne** [SullyChen/Autopilot-TensorFlow#29]
Traceback (most recent call last):
  File "\Autopilot-TensorFlow-master\train.py", line 29, in <module>
    summary_writer = tf.train.Saver(logs_path, graph)
  File "\python 6\lib\site-packages\tensorflow\python\training\saver.py", line 1281, in __init__
    self.build()
  File "\python 6\lib\site-packages\tensorflow\python\training\saver.py", line 1293, in build
    self._build(self._filename, build_save=True, build_restore=True)
  File "\python 6\lib\site-packages\tensorflow\python\training\saver.py", line 1330, in _build
    build_save=build_save, build_restore=build_restore)
  File "\python 6\lib\site-packages\tensorflow\python\training\saver.py", line 756, in _build_internal
    saveables = self._ValidateAndSliceInputs(names_to_saveables)
  File "\python 6\lib\site-packages\tensorflow\python\training\saver.py", line 656, in _ValidateAndSliceInputs
    names_to_saveables = BaseSaverBuilder.OpListToDict(names_to_saveables)
  File "\python 6\lib\site-packages\tensorflow\python\training\saver.py", line 504, in OpListToDict
    "list: %s" % op_list)

**Comment by anianne** [comment]
Used the not yet approved pull request code so it would work.
