### ISSUE TITLE
tun.py scipy error

### ISSUE THREAD

**Issue by torontofangirl** [SullyChen/Autopilot-TensorFlow#41]
Running run.py. I made a few adjustments to the train and model scripts to make them compatible with tf 1.9. I am running python 3.6 and tesorflow-gpu==1.9

Traceback (most recent call last):
  File "run_dataset.py", line 21, in <module>
    call("clear")
  File "C:\Users\16175\AppData\Local\Programs\Python\Python36\lib\subprocess.py", line 287, in call
    with Popen(*popenargs, **kwargs) as p:
  File "C:\Users\16175\AppData\Local\Programs\Python\Python36\lib\subprocess.py", line 729, in __init__
    restore_signals, start_new_session)
  File "C:\Users\16175\AppData\Local\Programs\Python\Python36\lib\subprocess.py", line 1017, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] The system cannot find the file specified

P.S. I just realized I spelt run wrong in the title :(

**Comment by torontofangirl** [comment]
nevermind. solved by adding 'shell=True' into thr call arg.
